"""
Django settings for my_tech_start project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(4#a1iczbip=u)anj54$id1w#sh63-mrhuqlwie(btsmp@08gb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
LOGIN_REDIRECT_URL = 'index'
ALLOWED_HOSTS = ['*']
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
BACKGROUND_TASK_RUN_ASYNC = True
USE_TZ = True
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_L10N = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'channels',
    'base_tech',
    # 'background_task',
    'paytm',
    'rest_framework',
    'django_extensions',
    'vendor_side',
    'delivery_side',
    'django_crontab',
    'fcm_django'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
]

CRONJOBS = [
    ('15,30 6-18 * * *', 'base_tech.cron.place_subscribed_order')
]

ROOT_URLCONF = 'my_tech_start.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_tech_start.wsgi.application'
# ASGI_APPLICATION = 'my_tech_start.routing.application'
#ALLOWED_HOSTS = ['secure-plateau-67455.herokuapp.com']
# CSRF_USE_SESSIONS = True

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'kfgwalbu',
        'USER': 'kfgwalbu',
        'PASSWORD': 'CKlkIQuJnhykwHLNeXwN_uGE_AaT3Fh9',
        'HOST': 'rajje.db.elephantsql.com',
        'PORT': '5432',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'gocodeing',
#         'USER': 'priyash',
#         'PASSWORD': 'krish_55',
#         'HOST': 'postgresql-7165-0.cloudclusters.net',
#         'PORT': '7168',
#     }
# }


prod_db = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(prod_db)

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_ROOT, '..', 'staticfiles')
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(PROJECT_ROOT, '..', 'static'),
)

#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

PAYTM_MERCHANT_KEY = "#k@VukVkSWlfOOXT"
PAYTM_MERCHANT_ID = "zUPPzR66078013548661"
# HOST_URL = "http://hemantyadav.pythonanywhere.com/"
PAYTM_CALLBACK_URL = "paytm/response/"

if DEBUG:
    PAYTM_MERCHANT_KEY = "#k@VukVkSWlfOOXT"
    PAYTM_MERCHANT_ID = "zUPPzR66078013548661"
    PAYTM_WEBSITE = 'WEBSTAGING'
    # HOST_URL = 'http://hemantyadav.pythonanywhere.com/'


ALLOWED_HOSTS = {'*'}
# import django_heroku
# django_heroku.settings(locals())

FCM_DJANGO_SETTINGS = {
        "FCM_SERVER_KEY": "AAAA8jMZHHg:APA91bEfl3JV4tCn4FYPj7th3tzgNLTsU1QJDghjFgiyRG9XGcThyBXXhY_MIuUGqLc7Es7Uy0pqrfS-BMwl1G9QhBG7FRtEl3BZSNuSG-l-Y2zpXDZnK-7DNtxKV8YQ9F_rLIA5STCr"
}