# Generated by Django 2.2.6 on 2020-04-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_side', '0002_deliveryboyorders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboyorders',
            name='status',
        ),
    ]
