# Generated by Django 3.0.2 on 2020-02-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0002_geoh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoh',
            old_name='geoh',
            new_name='geoha',
        ),
    ]
