# Generated by Django 3.0.2 on 2020-02-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0003_auto_20200206_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='geoh',
        ),
        migrations.AddField(
            model_name='vendors',
            name='geoha',
            field=models.CharField(default='asdf34s', max_length=12),
            preserve_default=False,
        ),
    ]
