# Generated by Django 3.0.2 on 2020-02-19 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0005_auto_20200209_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delboy_type',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='delivery_boy_phone',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='vendor_phone',
        ),
        migrations.AddField(
            model_name='orders',
            name='pending_order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order_status', models.CharField(choices=[('D', 'Delivered'), ('A', 'Active')], default='A', max_length=50)),
                ('delboy_type', models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary')], default='S', max_length=50)),
                ('vendor_phone', models.CharField(blank=True, max_length=500, null=True)),
                ('delivery_boy_phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base_tech.Delivery_Boys')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_tech.Orders')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_tech.CategorizedProducts')),
            ],
        ),
    ]
