# Generated by Django 3.0.2 on 2020-02-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0007_auto_20200221_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geohash_distance',
            name='dist',
            field=models.FloatField(default=0),
        ),
    ]
