# Generated by Django 3.0.2 on 2020-02-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0008_auto_20200222_0149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='indep_Addresses',
        ),
        migrations.DeleteModel(
            name='iteminfo',
        ),
    ]
