# Generated by Django 3.0.2 on 2020-02-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0009_auto_20200225_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='order_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
