# Generated by Django 3.0.2 on 2020-02-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0011_auto_20200228_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='order_status',
        ),
    ]
