# Generated by Django 3.0.2 on 2020-02-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0012_remove_order_items_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cells',
            name='Cell_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
