# Generated by Django 3.0.2 on 2020-02-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0013_auto_20200228_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_boys',
            name='accepted_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
