# Generated by Django 3.0.2 on 2020-02-28 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0014_delivery_boys_accepted_or_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='primary_cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base_tech.Cells'),
        ),
    ]
