# Generated by Django 3.0.2 on 2020-03-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0015_orders_primary_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='primary_vendor2',
            field=models.CharField(default='123456', max_length=50),
        ),
    ]
