# Generated by Django 3.0.2 on 2020-03-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0016_orders_primary_vendor2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorizedproducts',
            name='product_imagepath',
        ),
    ]
