# Generated by Django 3.0.2 on 2020-03-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0017_remove_categorizedproducts_product_imagepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorizedproducts',
            name='product_imagepath',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
