# Generated by Django 3.0.2 on 2020-03-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0018_categorizedproducts_product_imagepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='size',
            field=models.FloatField(default=1),
        ),
    ]
