# Generated by Django 3.0.2 on 2020-03-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0020_auto_20200324_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribed_orders',
            name='delivery_month',
        ),
        migrations.AddField(
            model_name='subscribed_orders',
            name='duration',
            field=models.CharField(default='monthly', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribed_orders',
            name='pending_order',
            field=models.IntegerField(default=0),
        ),
    ]
