# Generated by Django 3.0.2 on 2020-03-25 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0021_auto_20200326_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='size',
        ),
        migrations.RemoveField(
            model_name='subscribed_order_items',
            name='size',
        ),
        migrations.CreateModel(
            name='Deliverying_Boys_subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorder_id', models.CharField(max_length=500)),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Order date')),
                ('order_time', models.TimeField(auto_now_add=True, verbose_name='Order time')),
                ('phone_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_tech.Delivery_Boys')),
            ],
        ),
    ]
