# Generated by Django 3.0.2 on 2020-03-26 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0022_auto_20200326_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverying_boys_subs',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected')], default='A', max_length=20),
        ),
        migrations.AddField(
            model_name='subscribed_orders',
            name='far_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base_tech.Vendors'),
        ),
    ]
