# Generated by Django 3.0.2 on 2020-03-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0023_auto_20200326_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribed_order_items',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
