# Generated by Django 3.0.2 on 2020-03-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0024_auto_20200326_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribed_order_items',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
