# Generated by Django 3.0.2 on 2020-03-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0026_subscribed_orders_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribed_orders',
            name='delivery_time',
        ),
    ]
