# Generated by Django 3.0.2 on 2020-03-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0027_remove_subscribed_orders_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed_orders',
            name='delivery_time',
            field=models.CharField(default='1:30', max_length=200),
            preserve_default=False,
        ),
    ]
