# Generated by Django 2.2.6 on 2020-03-31 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0028_subscribed_orders_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_boys',
            name='delboy_fcm_token',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='reguser',
            name='customer_fcm_token',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='subscribed_orders',
            name='completion_status',
            field=models.CharField(choices=[('C', 'Complete'), ('I', 'Incomplete')], default='C', max_length=20),
        ),
        migrations.AddField(
            model_name='subscribed_orders',
            name='order_time',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 31, 17, 47, 53, 620423, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendors',
            name='vendor_fcm_token',
            field=models.CharField(default='', max_length=500),
        ),
    ]
