# Generated by Django 2.2.6 on 2020-03-31 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0029_auto_20200331_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverying_boys_subs',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='deliverying_boys_subs',
            name='order_time',
        ),
    ]
