# Generated by Django 2.2.6 on 2020-03-31 18:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0030_auto_20200331_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverying_boys_subs',
            name='order_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 3, 31, 18, 3, 16, 325736, tzinfo=utc), verbose_name='Order date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverying_boys_subs',
            name='order_time',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 31, 18, 3, 24, 883214, tzinfo=utc), verbose_name='Order time'),
            preserve_default=False,
        ),
    ]
