# Generated by Django 2.2.6 on 2020-03-31 18:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0032_auto_20200331_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed_orders',
            name='order_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 3, 31, 18, 11, 47, 156101, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribed_orders',
            name='order_time',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 31, 18, 11, 52, 316116, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
