# Generated by Django 2.2.6 on 2020-03-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0033_auto_20200331_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribed_orders',
            name='completion_status',
        ),
    ]
