# Generated by Django 2.2.6 on 2020-03-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0034_remove_subscribed_orders_completion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed_orders',
            name='completion_status',
            field=models.CharField(choices=[('C', 'Complete'), ('I', 'Incomplete')], default='C', max_length=20),
        ),
    ]
