# Generated by Django 2.2.6 on 2020-04-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0038_auto_20200331_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_boys',
            name='delivery_imagepath',
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vendor_imagepath',
            field=models.ImageField(default='toys.png', upload_to='images/'),
        ),
    ]
