# Generated by Django 2.2.6 on 2020-04-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0039_auto_20200401_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='vendor_imagepath',
        ),
    ]
