# Generated by Django 2.2.6 on 2020-04-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0044_delivery_boys_delivery_imagepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverying_boys_subs',
            name='vendor_status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverying_boys_subs',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=20),
        ),
    ]
