# Generated by Django 2.2.6 on 2020-04-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0045_auto_20200401_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverying_boys_subs',
            name='otp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
