# Generated by Django 2.2.6 on 2020-04-02 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0046_deliverying_boys_subs_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed_orders',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 2, 11, 6, 11, 799896, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
