# Generated by Django 2.2.6 on 2020-04-03 14:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0047_subscribed_orders_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='city',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='house_no',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='street',
        ),
        migrations.AddField(
            model_name='addresses',
            name='address',
            field=models.CharField(default=datetime.datetime(2020, 4, 3, 14, 23, 24, 134582, tzinfo=utc), max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='category',
            field=models.CharField(default=datetime.datetime(2020, 4, 3, 14, 23, 28, 872294, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2020, 4, 3, 14, 23, 34, 645876, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
