# Generated by Django 2.2.6 on 2020-04-03 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0049_auto_20200403_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='address_id',
        ),
        migrations.AddField(
            model_name='addresses',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2020, 4, 3, 14, 26, 24, 105191, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
