# Generated by Django 2.2.6 on 2020-04-03 14:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0050_auto_20200403_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='id',
        ),
        migrations.AddField(
            model_name='addresses',
            name='address_id',
            field=models.IntegerField(default=datetime.datetime(2020, 4, 3, 14, 28, 21, 909906, tzinfo=utc), primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
