# Generated by Django 2.2.6 on 2020-04-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0053_auto_20200403_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='address_id',
        ),
        migrations.AddField(
            model_name='addresses',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
