# Generated by Django 2.2.6 on 2020-04-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0057_auto_20200403_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
