# Generated by Django 2.2.6 on 2020-04-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0061_auto_20200403_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='address',
        ),
    ]
