# Generated by Django 2.2.6 on 2020-04-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0062_remove_addresses_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='address',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
