# Generated by Django 2.2.6 on 2020-04-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0063_addresses_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverying_boys_subs',
            name='vendor_status',
        ),
    ]
