# Generated by Django 2.2.6 on 2020-04-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0064_remove_deliverying_boys_subs_vendor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverying_boys_subs',
            name='vendor_status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=20),
        ),
    ]
