# Generated by Django 2.2.6 on 2020-04-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0065_deliverying_boys_subs_vendor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverying_boys_subs',
            name='otp',
        ),
    ]
