# Generated by Django 2.2.6 on 2020-04-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0066_remove_deliverying_boys_subs_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverying_boys_subs',
            name='otp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
