# Generated by Django 2.2.6 on 2020-04-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0068_auto_20200404_1007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendors_subs',
        ),
    ]
