# Generated by Django 2.2.6 on 2020-04-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0070_vendors_subs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendors_subs',
        ),
    ]
