# Generated by Django 2.2.6 on 2020-04-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0072_vendors_subs'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors_subs',
            name='delivery_status',
            field=models.CharField(choices=[('P', 'Picked'), ('N', 'Not Picked')], default='N', max_length=20),
        ),
    ]
