# Generated by Django 2.2.6 on 2020-04-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0073_vendors_subs_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='delivery_status',
            field=models.CharField(choices=[('P', 'Picked'), ('N', 'Not Picked')], default='N', max_length=20),
        ),
    ]
