# Generated by Django 2.2.6 on 2020-04-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0074_order_items_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='address',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='category',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='pincode',
        ),
    ]
