# Generated by Django 2.2.6 on 2020-04-04 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0075_auto_20200404_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='address',
            field=models.CharField(default='123', max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='category',
            field=models.CharField(default='1324', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='latitude',
            field=models.FloatField(default='1234'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='longitude',
            field=models.FloatField(default='134'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='phone_no',
            field=models.ForeignKey(default='134', on_delete=django.db.models.deletion.CASCADE, to='base_tech.RegUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
