# Generated by Django 2.2.6 on 2020-04-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0077_addresses_house_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='city',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='landmark',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='street',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addresses',
            name='house_no',
            field=models.CharField(max_length=10),
        ),
    ]
