# Generated by Django 2.2.6 on 2020-04-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0078_auto_20200404_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='city',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='house_no',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='street',
        ),
    ]
