# Generated by Django 2.2.6 on 2020-04-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0079_auto_20200404_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
