# Generated by Django 2.2.6 on 2020-04-04 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0084_addresses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
