# Generated by Django 2.2.6 on 2020-04-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0086_addresses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
