# Generated by Django 2.2.6 on 2020-04-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0092_auto_20200405_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverying_boys_subs',
            name='otp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
