# Generated by Django 2.2.6 on 2020-04-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0093_deliverying_boys_subs_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverying_boys_subs',
            name='otp',
        ),
    ]
