# Generated by Django 2.2.6 on 2020-04-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0094_remove_deliverying_boys_subs_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='address_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
