# Generated by Django 3.0.2 on 2020-04-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0095_auto_20200406_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverying_boys_subs',
            name='vendor_status',
        ),
    ]
