# Generated by Django 3.0.2 on 2020-04-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0096_remove_deliverying_boys_subs_vendor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reguser',
            name='password',
        ),
        migrations.AddField(
            model_name='reguser',
            name='wallet_amt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
