# Generated by Django 3.0.2 on 2020-04-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0098_auto_20200409_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
