# Generated by Django 3.0.2 on 2020-04-13 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0101_subscribed_orders_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribed_orders',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
