# Generated by Django 3.0.2 on 2020-04-13 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0104_remove_subscribed_orders_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed_orders',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
