# Generated by Django 3.0.2 on 2020-04-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0105_subscribed_orders_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribed_orders',
            name='start_date',
            field=models.DateField(),
        ),
    ]
