# Generated by Django 3.0.2 on 2020-04-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0106_auto_20200413_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribed_orders',
            name='start_date',
            field=models.DateField(default=''),
        ),
    ]
