# Generated by Django 3.0.2 on 2020-04-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0108_remove_subscribed_orders_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribed_orders',
            name='end_date',
        ),
    ]
