# Generated by Django 3.0.2 on 2020-04-13 13:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0110_subscribed_orders_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed_orders',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 13, 13, 36, 41, 78687, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
