# Generated by Django 3.0.2 on 2020-04-13 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0113_remove_subscribed_orders_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed_orders',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='start_date'),
            preserve_default=False,
        ),
    ]
