# Generated by Django 3.0.2 on 2020-04-13 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0115_remove_subscribed_orders_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed_orders',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 4, 13)),
        ),
    ]
