# Generated by Django 3.0.2 on 2020-04-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0117_auto_20200413_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribed_orders',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
