# Generated by Django 3.0.2 on 2020-04-13 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0119_remove_subscribed_orders_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed_orders',
            name='strt_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 13, 14, 15, 22, 432485, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
