# Generated by Django 3.0.2 on 2020-04-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0120_subscribed_orders_strt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribed_orders',
            name='strt_date',
            field=models.CharField(default='s', max_length=100),
        ),
    ]
