# Generated by Django 3.0.2 on 2020-04-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0121_auto_20200413_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribed_orders',
            name='strt_date',
        ),
    ]
