# Generated by Django 2.2.5 on 2019-10-26 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prev_orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=uuid.uuid4, max_length=500)),
                ('vendor_phone', models.CharField(blank=True, max_length=500, null=True)),
                ('product_id', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected')], default='A', max_length=20)),
                ('order_status', models.CharField(choices=[('D', 'Delivered'), ('A', 'Active')], default='A', max_length=50)),
            ],
        ),
    ]
