# Generated by Django 2.2.5 on 2019-10-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_side', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prev_orders',
            name='nos',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
