# Generated by Django 2.2.5 on 2019-10-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_side', '0002_prev_orders_nos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prev_orders',
            name='nos',
        ),
    ]
